[package]
name = "git-clean-gone"
version = "0.1.2"
edition = "2024"
description = "A CLI tool to clean up local git branches whose remote tracking branch is gone"
homepage = "https://github.com/eldertorres/git-clean-gone"
repository = "https://github.com/eldertorres/git-clean-gone"

[dependencies]
colored = "3.0.0"
dialoguer = "0.12.0"
regex = "1.12.2"

# Config for 'dist'
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
cargo-dist-version = "0.30.2"
ci = "github"
installers = ["shell", "powershell"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
pr-run-mode = "plan"
